name: rapid
description: A chat application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  cloud_firestore: ^0.14.4
  firebase_messaging: ^7.0.3
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  http: ^0.12.2
  path: ^1.7.0
  sqflite: ^1.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
